Repository WELLCOME-DEV-WORKS/forms-next-app, pull requests merged in 2024-11, with the labels that each got.

#53 Style: 전반적인 alert 디자인 수정
  public/img/Magnify.svg
  src/app/userSurvey/page.tsx
  src/components/reservation/EventSwal.tsx
  src/components/userSurvey/NavigationButtons.tsx
  src/styles/globals.css
Labels: UI

#54 LoadingAlert 컴포넌트화, 비동기 지연 처리
  src/components/userSurvey/LoadingAlert.tsx
  src/components/userSurvey/NavigationButtons.tsx
Labels: Feature, Refactor

#55 LoadingAlert 비동기 지연 처리, 컴포넌트화
  src/app/reservation/page.tsx
  src/components/recommendation/RecommendationBtn.tsx
  src/components/recommendation/RecommendationForm.tsx
  src/components/userSurvey/NavigationButtons.tsx
  src/components/userSurvey/SurveyAnswer.tsx
  src/components/userSurvey/SurveyQuestion.tsx
Labels: Feature, Refactor

#58 Header DropdownMenu Mypage 추가
  src/components/ui/UserAccountNav.tsx
Labels: Feature
