Repository WELLCOME-DEV-WORKS/forms-next-app, pull requests merged in 2024-10, with the labels that each got.

#44 Refactor: 추천페이지 버튼 컴포넌트, 클릭 핸들러 분리
  src/app/recommendation/page.tsx
  src/components/recommendation/RecommendationBtn.tsx
  src/components/recommendation/RecommendationBtnHandler.tsx
  src/components/recommendation/RecommendationForm.tsx
  src/components/recommendation/RecommendationLogic.tsx
  src/store/SurveyStore.tsx
Labels: Refactor

#45 Style: 클릭한 버튼에 스타일 추가
  src/components/recommendation/RecommendationBtn.tsx
  src/components/recommendation/RecommendationBtnHandler.tsx
  src/components/recommendation/RecommendationForm.tsx
  src/components/recommendation/RecommendationLogic.tsx
Labels: UI

#46 Style: 추천페이지 반응형 적용
  src/app/recommendation/page.tsx
  src/components/recommendation/RecommendationBtn.tsx
  src/components/recommendation/RecommendationBtnHandler.tsx
  src/components/recommendation/RecommendationForm.tsx
Labels: UI

#49 Style: 버튼 디자인 적용
  src/app/userSurvey/page.tsx
  src/components/userSurvey/SurveyAnswer.tsx
Labels: UI

#50 다음 버튼 클릭시 selectedAnswer 초기화를 통한 유효성 검사 정상화
  src/app/userSurvey/page.tsx
Labels: BugFix

#51 마이페이지 UI 및 스타일 객체 처리
  src/app/mypage/page.tsx
  src/app/reservation/page.tsx
  src/components/mypage/TreatmentCard.tsx
Labels: UI

#52 추천 로직 개선 및 스타일 수정
  src/app/userSurvey/page.tsx
  src/components/recFlow/RecommendationList.tsx
  src/components/recommendation/RecommendationBtn.tsx
  src/components/recommendation/RecommendationForm.tsx
  src/components/recommendation/RecommendationLogic.tsx
  src/components/userSurvey/NavigationButtons.tsx
  src/components/userSurvey/SurveyAnswer.tsx
Labels: Refactor, UI
